### ISSUE TITLE
Allow multiple tabs

### ISSUE THREAD

**Issue by mrmartineau** [dmarmor/osx-chrome-ssb-gui#1]
Would it be possible to allow for multiple tabs in this SSB? 

P.S. really useful tool btw, cheers

**Comment by dmarmor** [comment]
Hey, glad the tool is proving useful. I'll look into the multiple tab situation. May take me a little while as this is definitely a spare-time project, but I'll keep you posted! Thanks for the feedback.

**Comment by mrmartineau** [comment]
Great, thanks but don't worry if its a massive hassle. Cheers

**Comment by dmarmor** [comment]
I looked into this a bit, and it is possible to have the SSB start with multiple tabs open. It will then not be in "app" mode--so you'll have the usual toolbar and address bar and everything when it opens, but it would launch every time with however many tabs you specified. Is that what you'd want?

If so, I need to figure out a good interface for specifying those tabs. AppleScript isn't fantastic in terms of user interface, so it might be a bit clunky, but should be possible.

**Comment by mrmartineau** [comment]
HI @dmarmor, thanks for looking into it. I don't mind having the address bar etc because I think it would be useful when using multiple tabs. My current workflow with Fluid (mac app) is to specify the primary tab (they only ask for one) and then I add more after the SSB has been setup. If you could do the same and save all open tabs when it is quit then I would defintely use it.

**Comment by mishtershmart** [comment]
+1. This would be an awesome addition, as I currently use Fluid for exactly the same thing. I'd much prefer a chrome-based SSB, however.

**Comment by dmarmor** [comment]
Hey guys--just wanted to let you know this functionality will be part of the next version (along with a bunch of other improvements). Can't give a specific estimate for when I'll have it done, but it's coming along...

**Comment by mrmartineau** [comment]
that's awesome, thanks @dmarmor

**Comment by dmarmor** [comment]
Hey guys, just wanted to let you know I've just posted version 2.0.0 of MakeChromeSSB, which incorporates your idea to allow multi-tab SSBs. The interface for creating a mult-tab SSB should be self-explanatory (though it's a bit clumsy given the modal dialog-based AppleScript interface). Anyway, please give it a try and please let me know if you find any problems or bugs. Thank you for the idea!

**Comment by mishtershmart** [comment]
Champion! So far, so good. 👍

**Comment by mrmartineau** [comment]
This is great, thanks @dmarmor. The dialogs are a little clumsy but I don't care, i think  you have done a great job :+1: :+1:

**Comment by dmarmor** [comment]
Excellent! Thanks guys. Glad it's all working so far. Do keep me posted on any bugs you find...
