### ISSUE TITLE
Duplicate tabs on reopen (v2)

### ISSUE THREAD

**Issue by mishtershmart** [dmarmor/osx-chrome-ssb-gui#4]
Howdy,

V2 is looking sweet as – thanks for your hard work. 

I've just noticed that tabs are being saved on close (what I would expect to happen), but upon reopen of the app, the default tabs are opened again as additional tabs.

Cheers

**Comment by dmarmor** [comment]
Hey, glad the new version is mostly working for you. So what I think is happening is that you have the SSB's preferences set with the "On Startup" setting "Continue where you left off." So when it runs, Chrome is telling the SSB to open whatever tabs you left open when you quit--but then the SSB is *also* opening the tabs you specified when you created it.

If you want the SSB to *only* open the specified tabs, set the "On Startup" preferences to "Open the New Tabs page. If you want it to only open the tabs you left open last time, then you need to recreate the SSB, use the "Browser Tabs" option, but then immediately click "Done (Don't Add)" so you haven't specified any tabs. Then the SSB will simply use whatever your Chrome prefs say (it'll basically just function like a second instance of Chrome).

Hope that made sense. Does that help?

Cheers,
  Dave

**Comment by dmarmor** [comment]
Hi again--did my previous comment answer your issue? If so, I'll close the issue...

Cheers,
  Dave
