### ISSUE TITLE
Error: Does not match .plist version.

### ISSUE THREAD

**Issue by bikeatefoucault** [dmarmor/osx-chrome-ssb-gui#5]
Went to create my first ssb with this tool (thank you by the way)

And received an "Error: Does not match .plist version." (paraphrased, sorry for the poor documentation, in the middle of my work day)

**Comment by thinkspill** [comment]
I got this today as well, first time using it.

**Comment by dmarmor** [comment]
Hi guys--can you give me the exact wording of that error? Or better yet, attach a screen capture of the error alert? I'm having a little trouble figuring out exactly what error you're getting. Thanks!

**Comment by thinkspill** [comment]
![ssberror](https://cloud.githubusercontent.com/assets/822133/8070765/ca7d038e-0eb8-11e5-9fcc-96b73155fefd.png)

**Comment by thinkspill** [comment]
![chromever](https://cloud.githubusercontent.com/assets/822133/8070791/07098426-0eb9-11e5-85cf-8fbb476de142.png)

**Comment by dmarmor** [comment]
Aha--thank you! I think I may know what's happening there. I will work on this today and see if I can get it fixed. Stay tuned...

**Comment by dmarmor** [comment]
Hey guys, I just posted 2.0.1 which should solve this problem. For now I'll close this issue. Please give it a try and we can reopen if you're still having problems. Thanks!
