### ISSUE TITLE
SSB not displaying 2x on retina screen 

### ISSUE THREAD

**Issue by mikejacobs** [dmarmor/osx-chrome-ssb-gui#7]
Not just the content, the entire application is blurry. Is this a build setting I may have missed? Awesome project by the way!

![upload](https://cloud.githubusercontent.com/assets/45419/8437203/699cb4a0-1f12-11e5-9c03-7e0ccdd8a7b0.png)
SSB is on the right (ignore the blurry Pinboard icon on the left)

**Comment by dmarmor** [comment]
Thanks for the feedback! I am sadly still using a non-retina MacBook Air, so I have no way of testing retina support.

I did a little online research, and might have a solution. Are you familiar with Info.plist files? If so, would you try adding this key to the Info.plist in one of your SSBs:

    <key>NSHighResolutionCapable</key>
    <true/>

You might have to drag the SSB to a different folder to get the system to recognize the change. Then launch, and see if it works. If it does, I'll add that to the next release.

Weirdly, Chrome's Info.plist (which I derive the SSB ones from) doesn't include this key, so I'm not sure why it manages to be retina-aware, but if this works I won't question it.

Thanks!

**Comment by Zettt** [comment]
@dmarmor Added `NSHighResolutionCapable` and restarted the app. Works in high-res now.

**Comment by dmarmor** [comment]
That's great! Thanks for testing it for me. If you don't mind using that as a temporary fix for your SSBs, I'll add that to the next release.

**Comment by mhwinkler** [comment]
Great timing. Fixed for me too! Just incase anybody is wondering, I edited the plist on the app generated by SSB by navigating to /Applications/MyShinyNewSSB.app/Contents/Info.plist and added the lines suggested just above the closing lines:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	... file contents ...
	<key>NSHighResolutionCapable</key>
	<true/>
</dict>
</plist>
```

**Comment by mikejacobs** [comment]
Works for me too. Thanks @dmarmor for the quick response!

**Comment by Zettt** [comment]
@dmarmor I don't mind. No problem. Looking forward to the official release. Is this fixed already? If yes, I think you can close this and be happy. ;-)

**Comment by dmarmor** [comment]
Yes! This is working and will be in the next release, which I'm hoping to have up in the next day or so. Thanks for the help!
